### ISSUE TITLE
samples 

### ISSUE THREAD

**Issue by dutchsing009** [innnky/so-vits-svc#1]
do you have any audio samples you can provide ?
你有音频样本吗 ？

**Comment by innnky** [comment]
目前效果不是很好

**Comment by dutchsing009** [comment]
ok I will close the issue and feel free to showcase them when they are ready. 

好的，我将结束这个问题，你可以展示他们时，他们准备好了。

**Comment by dutchsing009** [comment]
你好，是否有任何关于样本的新的更新？
如果能听到一些48khz或32khz的样本，那将是很了不起的。
target
source
then the conversion.    :)

**Comment by innnky** [comment]
https://huggingface.co/spaces/innnky/nyaru-svc-3.0 
https://huggingface.co/spaces/DoNotSelect/AI-minato_aqua

**Comment by dutchsing009** [comment]
我想告诉你，vsinger2的作者说该代码将在1月初发布，差不多是1月10-15日，他也在努力弄清楚并尝试多发言人训练，我希望你能想办法将即将发布的代码用于 "SVC"。因为原代码需要输入乐谱才能训练，而任何数据集的乐谱都很难获得。
请随时关闭该问题。

**Comment by dutchsing009** [comment]
@innnky 我想告诉你，vsinger2的作者说该代码将在1月初发布，差不多是1月10-15日，他也在努力弄清楚并尝试多发言人训练，我希望你能想办法将即将发布的代码用于 "SVC"。因为原代码需要输入乐谱才能训练，而任何数据集的乐谱都很难获得。
请随时关闭该问题。

**Comment by innnky** [comment]
我也等待vsinger2的代码很久了，我一直有在留意他们的仓库但一直没有更新，当他们代码更新后我会第一时间将其应用于svc

**Comment by dutchsing009** [comment]
非常感谢你的出色工作，先生🙌，你没有得到足够的感谢。我认为vsinger2的质量和 "SVC "将比 "diff-svc""so-vits-svc""FreeSVC "加起来还要好:)
