### ISSUE TITLE
4.0分支的预训练底模 G_0.pth 与 D_0.pth 的iteration为0，lr_scheduler会报错

### ISSUE THREAD

**Issue by SayaSS** [innnky/so-vits-svc#103]
需要把last_epoch=epoch_str - 2改为last_epoch=epoch_str - 1才不会报错

希望能把预训练底模的iteration改为1

**Comment by innnky** [comment]
底模的iteration我确实设置错了，不过我发现以后在代码里限制了下 
epoch_str = max(epoch_str, 1)
你没pull最新的代码吧
