### ISSUE TITLE
有做VITS TTS的吗，全网最好VITS中文项目在这里哦

### ISSUE THREAD

**Issue by MaxMax2016** [innnky/so-vits-svc#116]
全网效果最好的中文VITS项目，https://github.com/PlayVoice/vits_chinese

**Comment by Miuzarte** [comment]
有个大家都有的东西就你没有  你猜是什么

**Comment by MaxMax2016** [comment]
作者是我兄弟，咋了，这个项目里面还有我写的代码呢
![jietu](https://user-images.githubusercontent.com/16432329/222100856-cdd955ac-ad68-4460-bfa3-9cdbeae62c62.png)

**Comment by Miuzarte** [comment]
> 作者是我兄弟，咋了，这个项目里面还有我写的代码呢
> ![jietu](https://user-images.githubusercontent.com/16432329/222100856-cdd955ac-ad68-4460-bfa3-9cdbeae62c62.png)
> 

我还以为你没有妈妈 作者是你爹呢😄

**Comment by MaxMax2016** [comment]
@Miuzarte 我有妈妈，我还有个儿子就是你

**Comment by Miuzarte** [comment]
> @Miuzarte 我有妈妈，我还有个儿子就是你

干嘛，被骂了不服气啊😅，上来就往issue里丢小广告你了不起啊😅，sovits是干什么的vits是干什么的你分清了吗弟弟，你要是牛逼就去做个教程发视频给我长长眼，一上来就丢个链接加几个字你算个鸡巴啊🤣

**Comment by MaxMax2016** [comment]
走着瞧，我要弄不出个牛逼的教程我是你儿子

**Comment by MaxMax2016** [comment]
@eve2ptp @Miuzarte 用这我的代码，还在这里瞎BB

**Comment by Miuzarte** [comment]
> @eve2ptp @Miuzarte 用着我的代码，还在这里瞎BB，有本事别用啊，滚开啊，没求你们过来

我翻遍了[jaywalnut310/vits](https://github.com/jaywalnut310/vits)、[CjangCjengh/vits](https://github.com/CjangCjengh/vits)、[innnky/so-vits-svc](https://github.com/innnky/so-vits-svc)的contributer怎么没找你名字，来说说用了你什么代码，import吗

**Comment by MaxMax2016** [comment]
眼睛睁大些 https://github.com/innnky/so-vits-svc/issues/172 @Miuzarte
