### ISSUE TITLE
能不能弄成exe这种安装包啊

### ISSUE THREAD

**Issue by leeseean** [innnky/so-vits-svc#118]
代码看不懂不会用，做个gui吧

**Comment by NaruseMioShirakana** [comment]
你说的对，但是《exe》是由微软公司自主研发的一款全新开放Windows平台可执行文件。文件运行在一个被称作「Windows」的计算机系统，在这里，被盖茨选中的人将被授予「explorer」，导引「双击打开、一键使用」之力。你将扮演一位名为「一键用户」的神秘角色，在自由的使用中邂逅性格各异、问题独特的其他血压用户们，——同时，逐步发掘「喂饭」的真相。
