### ISSUE TITLE
生成hubert和f0的时候遇到CUDA out of memory是因为数据集太大了吗？

### ISSUE THREAD

**Issue by Sin2023-X** [innnky/so-vits-svc#12]
![Screen Shot 2023-01-09 at 13 42 54](https://user-images.githubusercontent.com/15793692/211248263-06d943ba-d840-4497-a157-ae268e6122d7.png)
请问一下，这种情况下是不是拆分数据集就好了？

**Comment by innnky** [comment]
数据集音频请切片至10s左右每条
