### ISSUE TITLE
数据保存问题

### ISSUE THREAD

**Issue by zjz020627** [innnky/so-vits-svc#15]
模型跑到3000次迭代了依旧没有自动保存 看了下代码好像没有进去判断逻辑那里 只要ctrlc直接就什么都没了 请问我是漏了什么没有做吗？我是按照你的方法依次执行的 是否有需要修改的配置

**Comment by innnky** [comment]
config里面eval_interval ，默认是1000step保存一次

**Comment by zjz020627** [comment]
训练中打印的Epoch是否就是step 我修改了配置文件中的eval_interval为10 但Epoch到10后并没有进行保存 多出来一个以.0结尾的很长的文件 我用的是你提供的colab

**Comment by innnky** [comment]
我刚刚重新测试了下colab，没有任何问题，完全会正常保存，我不知道你是不是改了什么东西，全默认反正是能正常保存模型的
