### ISSUE TITLE
导出的config无法用在moegoe上

### ISSUE THREAD

**Issue by mother-killer** [innnky/so-vits-svc#158]
是需要删什么代码吗？还是干脆就不能用moegoe？

**Comment by NaruseMioShirakana** [comment]
MoeGoe主要针对且只支持Tacotron2、Vits和EmotionalVits，也就是TTS（文本转语音）的项目，而不是这里的VC（语音转换）项目，如果要使用UI，可以前往[MoeTTS](https://github.com/luoyily/MoeTTS) 或 [MoeSS](https://github.com/NaruseMioShirakana/MoeSS)
