### ISSUE TITLE
强烈要求，仓库维护者恢复显示代码引用出处；删引用等于剽窃！！！

### ISSUE THREAD

**Issue by MaxMax2016** [innnky/so-vits-svc#172]
作者可不像你们这些维护者那么不厚道

![jietu](https://user-images.githubusercontent.com/16432329/222100856-cdd955ac-ad68-4460-bfa3-9cdbeae62c62.png)

**Comment by NaruseMioShirakana** [comment]
如果认为您的代码对此仓库有贡献且维护者由于疏忽没有标注你的代码，在相关代码的位置加上标注或在Readme文件中添加引用，本仓库欢迎其他开发者注名，感谢其他开发者的贡献。但Issue并是非用于宣传的地方，请不要在Issue进行宣传。
同时，该Issue下的回复我也会一一处理。

**Comment by dtx525942103** [comment]
您还想着VITS作者自己来给您的readme里面添加Referance吗？

**Comment by NaruseMioShirakana** [comment]
同时，请仔细阅读各个开源协议的内容以及GitHub的社区规范。

**Comment by MaxMax2016** [comment]
标注了OK了

**Comment by NaruseMioShirakana** [comment]
> 您还想着VITS作者自己来给您的readme里面添加Referance吗？VITS原仓库都没列出来。

仓库的简介早已写明：基于Vits

**Comment by MaxMax2016** [comment]
@NaruseMioShirakana https://github.com/openvpi/DiffSinger 给你参考，看看别人对原创的尊重。

**Comment by NaruseMioShirakana** [comment]
对于f0提取的相关代码，实际上为官方文档中就存在的代码，同时也是pyworld库提取f0的标准流程，那么请问，你是否占有了pyworld维护者的成果 [pyworld](https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder)
![image](https://user-images.githubusercontent.com/40709280/222654551-7426f9b9-c790-4221-a8d7-a9237ca86970.png)
同时，仓库所有者在早已在readme中标注了你的仓库，你在这里的言论是否是在无理取闹
![image](https://user-images.githubusercontent.com/40709280/222656765-99cf4e61-a2b5-4968-af8c-f99c7b5579a2.png)

**Comment by NaruseMioShirakana** [comment]
> @NaruseMioShirakana 你看清楚，coarse_f0的提出、coarse_f0的代码和背后的 idear（作为 svc 的输入）都是我的，你瞎扯什么pyworld

那么请问维护者是否没有标注出你的仓库地址

**Comment by MaxMax2016** [comment]
@NaruseMioShirakana 你说标了，然后，你把那个评论删除了

**Comment by NaruseMioShirakana** [comment]
> @NaruseMioShirakana 你说标了，然后，你把那个评论删除了

请问，我删除了哪些内容呢

**Comment by MaxMax2016** [comment]
别和我说了，无耻的人，我错在、在这里推广微软改进VITS的优化方法，你继续剽窃啊

**Comment by NaruseMioShirakana** [comment]
> 

请指出我删除该信息的证据，我看了commit history，我并没有对readme文件做出任何“删减”修改。

**Comment by NaruseMioShirakana** [comment]
请指出我删除该信息的证据，我查阅了comment history，我并没有对readme文件做出任何“删减”修改。

**Comment by NaruseMioShirakana** [comment]
请指出我删除该信息的证据，我查阅了commits history，我并没有对readme文件做出任何“删减”修改。请不要给别人扣帽子

**Comment by NaruseMioShirakana** [comment]
> 别和我说了，无耻的人，我错在、在这里推广微软改进VITS的优化方法，你继续剽窃啊

还有请问，Issue的作用是什么，是不是用来让你打广告用的？
请遵守最基础的社区规则。

**Comment by MaxMax2016** [comment]
你没这个资格这么说

**Comment by NaruseMioShirakana** [comment]
> @NaruseMioShirakana 你说标了，然后，你把那个评论删除了

如果你认为我删除了你的广告这个做法不正确，那么请问，我可以在你的仓库issue中推广我的项目吗？

**Comment by MaxMax2016** [comment]
@NaruseMioShirakana 欢迎来推广优质项目

**Comment by NaruseMioShirakana** [comment]
> @NaruseMioShirakana 欢迎来推广优质项目，你删除的是这个issues里面的一个评论，评论的内容是：在代码中注明了引用的项目地址

由于我在这个issue中发现了攻击性言论，所以我无差别的删除了所有的评论，如果在这里存在误会希望可以在此解除误会

**Comment by MaxMax2016** [comment]
好的

**Comment by NaruseMioShirakana** [comment]
> 你没这个资格这么说，广告的目的是挣钱，我推广技术挣你啥钱了，我没去推广技术就没这个SO-VITS-SVC项目

我并不是反对推广，而是单纯的认为推广的地方不太正确，Issue在我看来是用来解决用户问题，反馈BUG和提出自己对新功能需求的地方，而不是用于推广。所以可能我们存在一些比较大的误会了

**Comment by eve2ptp** [comment]
作者又不是没标引用，自己先跑来issue区发广告，没给你ban了算好了。
想推广自己做好视频去社交平台推不比这更快？扎布多德勒

**Comment by MaxMax2016** [comment]
@eve2ptp 没你说话的份

**Comment by eve2ptp** [comment]
@MaxMax2016 继续期待你的《全网最好的Vits》😅，你上个issue的评论截图还在呢😅

**Comment by MaxMax2016** [comment]
@eve2ptp 不要偷换概念，我的是《有做VITS TTS的吗，全网最好VITS中文项目在这里哦 》

**Comment by MaxMax2016** [comment]
@eve2ptp 欢迎用你做的东西来对比，来测评

**Comment by MaxMax2016** [comment]
哼！！！

https://user-images.githubusercontent.com/16432329/223148035-7ddc2278-1887-437c-bc27-03a523de1869.mp4
