### ISSUE TITLE
请问各位大佬重新开始训练后step变为1怎么解决呀

### ISSUE THREAD

**Issue by ha1keyi** [innnky/so-vits-svc#194]
之前停止了训练，后来继续的时候发现step又从1开始了
而且一开始还加载了之前的checkpoint
<img width="421" alt="微信图片_20230306195221" src="https://user-images.githubusercontent.com/125971186/223102877-dbe4f37c-4df6-4f2e-aa49-294d665545cb.png">
<img width="482" alt="b7aa8dac94beb90c3182cd0fbda46e1" src="https://user-images.githubusercontent.com/125971186/223103134-69e4b394-b35c-4a83-aac8-700d78cc30a3.png">

**Comment by ha1keyi** [comment]
解决了，只要把train.py里的skip_optimizer = True改为False就行了

**Comment by innnky** [comment]
是的，这个选项我调试代码的时候用的，push上来忘了关了，，

**Comment by innnky** [comment]
现在已经改了
