### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by XiaoMiku01** [innnky/so-vits-svc#2]
使用 nyarumul 预模型训练时
https://github.com/innnky/so-vits-svc/blob/56c29e3ed82a42a5a9b709cf7067d6685559aa7e/data_utils.py#L373 的 len_bucket 可能为 0
导致 https://github.com/innnky/so-vits-svc/blob/56c29e3ed82a42a5a9b709cf7067d6685559aa7e/data_utils.py#L379 报错 
不知是否为训练集有错导致的

**Comment by XiaoMiku01** [comment]
调试发现 self.buckets 的第一项是空列表

**Comment by innnky** [comment]
应该修复了
