### ISSUE TITLE
我的模型在Windows 11上无法保存。

### ISSUE THREAD

**Issue by cheezebone** [innnky/so-vits-svc#23]
我试着在Windows 11上训练，但即使在1000个epochs之后，模型也没有保存。它不在本地或colab上保存模型。我不知道哪里出了问题。我知道github上有一个类似的问题，但是我只做了readme上说的，还是没有保存。

**Comment by innnky** [comment]
请提供更详细的信息，例如config文件，又比如训练时候的日志

**Comment by innnky** [comment]
还有，是日志输出上面明确写的Epoch: 1000，还是1000step，如果是1000epoch我怀疑你的数据数量有问题,filelists/train.txt是不是空的？

**Comment by cheezebone** [comment]
这就解决了问题。由于某些原因，train.txt是空的，但现在当我手动编辑它时，它就工作了。谢谢你的回答。
