### ISSUE TITLE
双卡训练会报加载错误

### ISSUE THREAD

**Issue by comacube** [innnky/so-vits-svc#24]
`(python3) D:\so-vits-svc-main\so-vits-svc-main>python train.py -c configs/config.json -m 48k
INFO:48k:{'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 12, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 17920, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 384, 'port': '8001'}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 48000, 'filter_length': 1280, 'hop_length': 320, 'win_length': 1280, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 2}, 'spk': {'sawako': 0}, 'model_dir': './logs\\48k'}
WARNING:48k:D:\so-vits-svc-main\so-vits-svc-main is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 1
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
INFO:torch.distributed.distributed_c10d:Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
./logs\48k\G_0.pth
./logs\48k\G_0.pth
INFO:48k:Loaded checkpoint './logs\48k\G_0.pth' (iteration 1)
./logs\48k\D_0.pth
INFO:root:Loaded checkpoint './logs\48k\G_0.pth' (iteration 1)
./logs\48k\D_0.pth
INFO:48k:Loaded checkpoint './logs\48k\D_0.pth' (iteration 1)
INFO:root:Loaded checkpoint './logs\48k\D_0.pth' (iteration 1)
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [64, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [64, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:48k:Train Epoch: 1 [0%]
INFO:48k:[1.987928867340088, 3.165637493133545, 9.151036262512207, 31.82508659362793, 2.3169174194335938, 0, 0.0001]
INFO:48k:Saving model and optimizer state at iteration 1 to ./logs\48k\G_0.pth
INFO:48k:Saving model and optimizer state at iteration 1 to ./logs\48k\D_0.pth
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    main()
  File "train.py", line 49, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\so-vits-svc-main\so-vits-svc-main\train.py", line 112, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "D:\so-vits-svc-main\so-vits-svc-main\train.py", line 131, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\so-vits-svc-main\so-vits-svc-main\data_utils.py", line 87, in __getitem__
    return self.get_audio(self.audiopaths[index][0])
  File "D:\so-vits-svc-main\so-vits-svc-main\data_utils.py", line 49, in get_audio
    spec = torch.load(spec_filename)
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
`
将 train_loader = DataLoader(train_dataset, num_workers=8, shuffle=False, pin_memory=True,
                              batch_size=hps.train.batch_size)
中workers设置成0仍然报错

目前可以指定os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'运行

**Comment by NaruseMioShirakana** [comment]
报错的重点在于：
```
File "D:\so-vits-svc-main\so-vits-svc-main\data_utils.py", line 49, in get_audio
spec = torch.load(spec_filename)
File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\serialization.py", line 795, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "C:\Users\Administrator\anaconda3\envs\python3\lib\site-packages\torch\serialization.py", line 1002, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```
他这里是在载入你预处理的spec.pt的时候发现这个文件为空。
也就是在读取spec.pt的开头就遇到了EOF。
而Vits源仓库是不会预处理数据的，数据的预处理（生成spec.pt）是在训练的第一个epoch的同时进行的（边训练边预处理），如果文件已经存在，则不创建spec.pt，而是从中直接读取。
这就造成了一个分布式训练的问题（类似于多线程IO），我们把工作中的两个线程命名为0和1
假如说线程0和线程1正好在第一epoch训练到了同一个文件，线程0首先会创建一个spec文件，然后在其写入文件之前，线程1检测到了文件已经存在，所以会从线程0创建的空文件（还来不及写入）中直接读取数据，然后就读取到了一个空文件。
所以解决这个问题的方法就是再次打乱trainloader的顺序，或者是在训练之前将所有的spec文件全部生成完毕。
重开一遍训练，看看是否可行，如果不可行就先用单GPU跑一轮，然后再开多GPU

**Comment by NaruseMioShirakana** [comment]
所以说这个问题可以看做是个VITS的历史遗留问题了（）

**Comment by comacube** [comment]
怪不得，我用单卡训练一个epoch之后 再改用双卡就可以了
