### ISSUE TITLE
数据集预处理失败

### ISSUE THREAD

**Issue by Lewellyns** [innnky/so-vits-svc#25]
![Screenshot_20230123_114455](https://user-images.githubusercontent.com/116251432/213962796-821cf5c0-ae5f-4223-bf02-d0d226179391.jpg)
划分训练集报错:Traceback (most recent call last):
  File "preprocess_flist_config.py", line 81, in <module>
    for speaker in tqdm(os.listdir(args.source_dir)):
FileNotFoundError: [Errno 2] No such file or directory: './dataset/32k'
除了数据集名称其它参数都是默认。

**Comment by innnky** [comment]
数据集是空的，你没放数据，或是放的位置不对
