### ISSUE TITLE
Add more details in readme, annotations in codes and optimize a lot of codes in original version

### ISSUE THREAD

**Issue by Typologi** [innnky/so-vits-svc#3]
Modify codes for any one who has a powerful GPU in its own computer and don't want to use jupyter to train this neural network. When this work finished, user can simply execute `process_datasets.bat` or `process_datasets.sh` for train data generation and `train.bat` or `train.sh` for model training.
Still in development, will it be possible to merge future?
[Fork Version](https://github.com/Typologi/so-vits-svc-documentation)

**Comment by innnky** [comment]
这注释和文档太强了！合并的话你直接提pr就行

**Comment by Typologi** [comment]
> 

吼

**Comment by Typologi** [comment]
> 这注释和文档太强了！合并的话你直接提pr就行

后面我写好测试完了会提交 PR 的。
