### ISSUE TITLE
希望提供48k版本的gradio支持

### ISSUE THREAD

**Issue by techzealot** [innnky/so-vits-svc#30]
希望main分支也提供sovits_gradio.py支持，这样在colab等中就可以比较容易的实现32K和48K的推理部分支持

**Comment by techzealot** [comment]
由于本人不懂python和ai相关内容，请问32k的gradio文件是否可以将如下41行32000改为48000直接使用（不考虑48k相关模型文件和配置）
[[https://huggingface.co/spaces/innnky/nyaru-svc-3.0/blob/main/app.py](url)](https://huggingface.co/spaces/innnky/nyaru-svc-3.0/blob/main/app.py#L41)
我测试了下好像可以，如果不修改输出会很怪

**Comment by NaruseMioShirakana** [comment]
可以自己改代码
将[models](models.py)中
```json
hps = {
        "sampling_rate": 32000,
        "inter_channels": 192,
        "resblock": "1",
        "resblock_kernel_sizes": [3, 7, 11],
        "resblock_dilation_sizes": [[1, 3, 5], [1, 3, 5], [1, 3, 5]],
        "upsample_rates": [10, 8, 2, 2],
        "upsample_initial_channel": 512,
        "upsample_kernel_sizes": [16, 16, 4, 4],
        "gin_channels": 256,
    }
```
的sampling_rate改为48000，然后将[infer_tool](inference/infer_tool.py)中infer函数中的x_tst = torch.repeat_interleave(x_tst, repeats=2, dim=1).transpose(1, 2)改为x_tst = torch.repeat_interleave(x_tst, repeats=3, dim=1).transpose(1, 2)

**Comment by techzealot** [comment]
> 

多谢回复，我是在main分支(48K)下复制这个app.py来使用的，看了下main分支确实如你所说修改了上述部分，现在是想将32K分支下的gradio实现迁移到48K下，尝试了将app.py41行32000改为48000，输出正常，只是不确定理论上是否可行，所以想确认一下

**Comment by techzealot** [comment]
> 

     您好，可能我描述的不够准确，我现在使用git main分支代码训练了模型，现在想在huggingface中实现gradio支持，发现在huggingface中已经有了32K实现，现在想把它改成支持48K模型。
    您所说的要修改内容在git main分支的代码中已经修改了，我现在想做的是将上述huggingface仓库下的app.py改成支持48K模型，经测试将app.py41行32000改为48000后输出正常，只是不确定理论上是否正确，特此求证

**Comment by techzealot** [comment]
@NaruseMioShirakana 

您好，可能我描述的不够准确，我现在使用git main分支代码训练了模型，现在想在huggingface中实现gradio支持，发现在huggingface中已经有了32K实现，现在想把它改成支持48K模型。

您所说的要修改内容在git main分支的代码中已经修改了，我现在想做的是将上述huggingface仓库下的app.py复制到git main分支下使用改成支持48K模型，经测试将app.py41行32000改为48000后输出正常，只是不确定理论上是否正确，特此求证

**Comment by mccleaner** [comment]
按上述步骤操作之后，速度依然有变化
联动：https://github.com/innnky/so-vits-svc/issues/9

**Comment by mccleaner** [comment]
> 按上述步骤操作之后，速度依然有变化 联动：#9

同时也需要改动grad文件的resize2d_f0和repeats
