### ISSUE TITLE
运行训练文件时出现 assert torch.cuda.is_available(), "CPU training is not allowed."

### ISSUE THREAD

**Issue by dianlang** [innnky/so-vits-svc#34]
assert torch.cuda.is_available(), "CPU training is not allowed."
谷歌也查不到只能来问下大佬们了！

**Comment by innnky** [comment]
训练需要GPU，CPU不能训练

**Comment by mimikwoomy** [comment]
But, how do you use GPU instead of CPU?
你如何使用 GPU 而不是 CPU？
