### ISSUE TITLE
数据保存问题

### ISSUE THREAD

**Issue by WhalerO** [innnky/so-vits-svc#36]
你好，我在训练时发现中断训练后重新加载时模型的保存好像出了一点问题。

 `2023-02-01 22:27:30,272	32k	INFO	Loaded checkpoint './logs\32k\G_1000.pth' (iteration 1)`
`2023-02-01 22:27:34,601	32k	INFO	Loaded checkpoint './logs\32k\D_1000.pth' (iteration 1)`
`2023-02-01 22:27:53,202	32k	INFO	Train Epoch: 1 [0%]`
`2023-02-01 22:27:53,202	32k	INFO	[2.4211788177490234, 2.3890013694763184, 9.296989440917969, 21.983633041381836, 1.29080331325531, 0, 0.0001]`
`2023-02-01 22:27:56,096	32k	INFO	Saving model and optimizer state at iteration 1 to ./logs\32k\G_0.pth`
`2023-02-01 22:27:56,974	32k	INFO	Saving model and optimizer state at iteration 1 to ./logs\32k\D_0.pth`

模型在读取G_1000.pth的checkpoint后保存到了G_0.pth中，训练似乎也重新开始了，请问这是否属于正常情况？

**Comment by innnky** [comment]
正常，G_1000第一个epoch还没走完，读取的时候step是按照epoch*(每ep下step数量) 方案计算当前step，因此算出来是0
https://github.com/innnky/so-vits-svc/blob/a5466ecdc94ea76e9f85f7ce7874e518513436f2/train.py#L96

**Comment by WhalerO** [comment]
谢谢！
