### ISSUE TITLE
推理步骤， 运行python inference_main.py报错, 显存不足?

### ISSUE THREAD

**Issue by Astro-Lee** [innnky/so-vits-svc#43]
推理步骤， 运行`python inference_main.py`报错, 显存不足?
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 9.93 GiB (GPU 0; 12.00 GiB total capacity; 8.22 GiB already allocated; 393.00 MiB free; 9.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by xbclub** [comment]
我也是 16g显存都不够用

**Comment by Astro-Lee** [comment]
估计是模型太大了

**Comment by innnky** [comment]
请使用32khz模型以节省显存，如果32khz依然爆显存请手动把音频切片后逐条转换

**Comment by xbclub** [comment]
python.exe .\train.py -c .\configs\config.json -m 32k 用的32k模型
然后 batch_size 设置为1 照样爆显存

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.10 GiB (GPU 0; 16.00 GiB total capacity; 8.90 GiB already allocated; 5.82 GiB free; 8.97 GiB rese
rved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

显卡是 3080ti 16g显存

**Comment by innnky** [comment]
> python.exe .\train.py -c .\configs\config.json -m 32k 用的32k模型 然后 batch_size 设置为1 照样爆显存
> 
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.10 GiB (GPU 0; 16.00 GiB total capacity; 8.90 GiB already allocated; 5.82 GiB free; 8.97 GiB rese rved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> 显卡是 3080ti 16g显存

训练爆显存的话，你试试回滚到这个版本是否有问题，这个版本应该基本代码应该肯定是好的 https://github.com/innnky/so-vits-svc/tree/178ad58e9dafceed7f4bf469010c64b2b240fefb，如果还爆显存我认为是你的训练数据问题，例如是否有将数据集切片至2-10s，等等

**Comment by xbclub** [comment]
> > python.exe .\train.py -c .\configs\config.json -m 32k 用的32k模型 然后 batch_size 设置为1 照样爆显存
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 8.10 GiB (GPU 0; 16.00 GiB total capacity; 8.90 GiB already allocated; 5.82 GiB free; 8.97 GiB rese rved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > 显卡是 3080ti 16g显存
> 
> 训练爆显存的话，你试试回滚到这个版本是否有问题，这个版本应该基本代码应该肯定是好的 https://github.com/innnky/so-vits-svc/tree/178ad58e9dafceed7f4bf469010c64b2b240fefb 如果还爆显存我认为是你的训练数据问题，例如是否有将数据集切片至2-10s，等等

我重新切片到15秒目前没爆显存问题
