### ISSUE TITLE
一键colab 48k克隆分支问题

### ISSUE THREAD

**Issue by Fitz161** [innnky/so-vits-svc#44]
一键colab 在使用48k分支训练时，第一个单元格选中48k后克隆下来的仍是32k分支，此时运行下方代码时会产生错误。希望能在命令中指定克隆的分支。

**Comment by innnky** [comment]
哦我知道了训练部分好像确实没改过来，我现在改下

**Comment by Fitz161** [comment]
应该是我这边没设置好，脚本没什么问题
