### ISSUE TITLE
跨平台训练问题

### ISSUE THREAD

**Issue by Fitz161** [innnky/so-vits-svc#45]
linux环境下训练的模型转到windows环境下继续训练时会出现错误，调试发现 `filename.split(os.sep)[-2]` 使用 `\\` 作为分隔符切割以 `/` 为分割的路径，产生了错误，建议使用更优雅的 `os.path.split`，以避免产生该问题。

**Comment by innnky** [comment]
我最新的版本全部统一使用 / 做分隔符了，os.path.split 的话，如果再win预处理后的文件有”\\“, 再到linux训练这样应该也会出问题吧
