### ISSUE TITLE
inference出现的问题

### ISSUE THREAD

**Issue by HungryKonata** [innnky/so-vits-svc#54]
训练完成后!python inference_main.py提示

Traceback (most recent call last):
  File "inference_main.py", line 10, in <module>
    from inference import infer_tool
  File "/content/so-vits-svc/inference/infer_tool.py", line 9, in <module>
    import maad
ModuleNotFoundError: No module named 'maad'

缺少maad模块，但是pip install maad又提示
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement maad (from versions: none)
ERROR: No matching distribution found for maad

这应该如何解决？

**Comment by innnky** [comment]
pip install scikit-maad
