### ISSUE TITLE
Windows下数据预处理重采样出错

### ISSUE THREAD

**Issue by NaN-NULL** [innnky/so-vits-svc#6]
在Windows下进行数据预处理重采样时文件路径错误
https://github.com/innnky/so-vits-svc/blob/041b44130c2792b8b1a9384a6d933b0f29509072/resample.py#L15
判断为False,导致文件没有被重采样
![image](https://user-images.githubusercontent.com/89097234/206288401-acda3deb-bb1b-4697-b0f5-2fa93ea60d41.png)
Linux下正常
应该是
https://github.com/innnky/so-vits-svc/blob/041b44130c2792b8b1a9384a6d933b0f29509072/resample.py#L13
在Windows下没有正确的split出speaker导致的

**Comment by innnky** [comment]
简单修了一下，但我手头没win电脑，你看看好了没？

**Comment by NaN-NULL** [comment]
好了
