### ISSUE TITLE
Colab中，训练时TensorBoard面板不随代数递进而改变

### ISSUE THREAD

**Issue by ldcivan** [innnky/so-vits-svc#61]
如题。或者说有其他方式获知训练进展吗。
<img width="954" alt="微信截图_20230209184623" src="https://user-images.githubusercontent.com/69411867/217791197-d1f2bbb3-c033-4a67-be97-7a86baac4a08.png">

**Comment by SuCicada** [comment]
同样的问题，请问你是怎么解决的呢
