### ISSUE TITLE
请问在Colab出现 "CPU training is not allowed."该如何解决

### ISSUE THREAD

**Issue by PeolpeRepublic** [innnky/so-vits-svc#66]
如图
<img width="1280" alt="屏幕截图_20230210_124018" src="https://user-images.githubusercontent.com/64297616/218002323-e35e52ec-e27c-45ef-8ef1-a8f6af05a8ea.png">

**Comment by zwzheng45** [comment]
代码执行程序→更改运行时类型→硬件加速程序选择GPU
<img width="417" alt="图片" src="https://user-images.githubusercontent.com/62459108/218317946-4d955c02-6b16-4714-aaaf-b4043e613936.png">

**Comment by PeolpeRepublic** [comment]
谢谢大佬
