### ISSUE TITLE
推理比较长的音频会爆显存

### ISSUE THREAD

**Issue by NaN-NULL** [innnky/so-vits-svc#7]
在进行推理时输入音频较长且中间没有停顿导致切出的slice较长，大约超过50s左右时会用尽16G显存。

**Comment by innnky** [comment]
可以试着调高推理的slice_db到-30，如果还不行就只能手动切片分段合成了

**Comment by NaN-NULL** [comment]
感觉应该是要手动切片了，试了试自动切发现断开的地方效果不是很好😿

**Comment by NaN-NULL** [comment]
最后转为CPU推理了，内存比显存大些😿

**Comment by SixInternet** [comment]
> 最后转为CPU推理了，内存比显存大些😿，CPU推理速度也不算太慢，基本60秒的音频60秒能推理出来
怎么切换成CPU推理呀，找不到在哪改

**Comment by NaN-NULL** [comment]
把CUDA设备隐藏，inference文件夹里面有个infer_tool.py，在21行下面加一行代码：os.environ["CUDA_VISIBLE_DEVICES"] = "-1" 应该就行了
