### ISSUE TITLE
48k分支推理出来的音频会加速？

### ISSUE THREAD

**Issue by gouku** [innnky/so-vits-svc#9]
推理出来的音频是加速了的，请问大概是哪里出了问题？

另外其实想问下32k和48k比能差多少？听感上如果感受不到区别的话我就不考虑用48k了。

**Comment by innnky** [comment]
个人感觉32k和48k听不出太大差别，至于音频加速，我怀疑是采样率之类的设置问题，我刚刚自己推理了一下应该是没有问题的

**Comment by DJGenshin** [comment]
我也遇到了，我是32k推理减速…

**Comment by innnky** [comment]
> 我也遇到了，我是32k推理减速…

我刚刚又测试了下32k，我这也没问题，请检查你config里采样率是否正确，如果还是不行往前回滚一个commit，那个代码100%是没问题的

**Comment by DJGenshin** [comment]
> 
感谢，已经解决了，之前偷懒把48k里改成cpu推理的inference_tool直接复制过来了，楼主可能也是这个问题

**Comment by Starlento** [comment]
我也碰到这个问题，用的是最新的代码（32k的branch），然后用的模型是下面链接的：
https://huggingface.co/spaces/DoNotSelect/AI-minato_aqua
他的模型应该是48K，并且config里面也是48000。
我也尝试切换到main branch也是一样的问题。

我尝试把他的inference文件夹复制过来，就是正常的。
但是我看inference里面最早的更新都是一周前了...
不知道是不是兼容性的问题，请问有没有什么办法可以fix（除了回滚代码）？

**Comment by innnky** [comment]
> 我也碰到这个问题，用的是最新的代码（32k的branch），然后用的模型是下面链接的： https://huggingface.co/spaces/DoNotSelect/AI-minato_aqua 他的模型应该是48K，并且config里面也是48000。 我也尝试切换到main branch也是一样的问题。
> 
> 我尝试把他的inference文件夹复制过来，就是正常的。 但是我看inference里面最后一次更新都是一周前了... 不知道是不是兼容性的问题，请问有没有什么办法可以fix（除了回滚代码）？

你是说换了inference文件夹就好了？我inference目录里面应该最近就更新过一次切片机（切片速度提升了几百倍），其他都没有任何改动，但是为啥切片机会导致音频加速，，还有加速是怎么个加速法，加速的同时音调也变了还是不变调，还是啥

**Comment by Starlento** [comment]
> > 我也碰到这个问题，用的是最新的代码（32k的branch），然后用的模型是下面链接的： https://huggingface.co/spaces/DoNotSelect/AI-minato_aqua 他的模型应该是48K，并且config里面也是48000。 我也尝试切换到main branch也是一样的问题。
> > 我尝试把他的inference文件夹复制过来，就是正常的。 但是我看inference里面最后一次更新都是一周前了... 不知道是不是兼容性的问题，请问有没有什么办法可以fix（除了回滚代码）？
> 
> 你是说换了inference文件夹就好了？我inference目录里面应该最近就更新过一次切片机（切片速度提升了几百倍），其他都没有任何改动，但是为啥切片机会导致音频加速，，还有加速是怎么个加速法，加速的同时音调也变了还是不变调，还是啥

我又确认了一下是什么东西生效的...是infer_tool的这两个内容：
f0 = resize2d_f0(f0, soft.shape[0]*3)
x_tst = torch.repeat_interleave(x_tst, repeats=3, dim=1).transpose(1, 2)

我现在有两个模型，一个是32K，一个是48K，config应该都是对的。
用现在最新代码：
48K的aqua，加速是22秒变成了15秒，音调也变了。
32K的taffy没问题。
然后我用了他的infer_tool之后：
aqua对了。
但是用32k的taffy的时候，22秒变成了33秒。

**Comment by innnky** [comment]
> > > 我也碰到这个问题，用的是最新的代码（32k的branch），然后用的模型是下面链接的： https://huggingface.co/spaces/DoNotSelect/AI-minato_aqua 他的模型应该是48K，并且config里面也是48000。 我也尝试切换到main branch也是一样的问题。
> > > 我尝试把他的inference文件夹复制过来，就是正常的。 但是我看inference里面最后一次更新都是一周前了... 不知道是不是兼容性的问题，请问有没有什么办法可以fix（除了回滚代码）？
> > 
> > 
> > 你是说换了inference文件夹就好了？我inference目录里面应该最近就更新过一次切片机（切片速度提升了几百倍），其他都没有任何改动，但是为啥切片机会导致音频加速，，还有加速是怎么个加速法，加速的同时音调也变了还是不变调，还是啥
> 
> 我又确认了一下是什么东西生效的...是infer_tool的这两个内容： f0 = resize2d_f0(f0, soft.shape[0]*3) x_tst = torch.repeat_interleave(x_tst, repeats=3, dim=1).transpose(1, 2)
> 
> 我现在有两个模型，一个是32K，一个是48K，config应该都是对的。 用现在最新代码： 48K的aqua，加速是22秒变成了15秒，音调也变了。 32K的taffy没问题。 然后我用了他的infer_tool之后： aqua对了。 但是用32k的taffy的时候，22秒变成了33秒。

32k和48k的infer_tool 本来是不一样的，32k模型 repeats=2， 48k模型 repeats=3，我main分支就是3，32k分支就是2，所以说32k模型就用32k分支去推理，48k模型用main分支去推理肯定是没问题的
